# Generated by Django 2.2.12 on 2023-02-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='book',
            name='last_name',
            field=models.CharField(default='Толстой Лев', max_length=200),
            preserve_default=False,
        ),
    ]
