# Generated by Django 2.2.12 on 2023-02-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20230216_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_published',
            field=models.DateField(auto_now=True),
        ),
    ]
