# Generated by Django 2.2.12 on 2023-02-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20230218_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.IntegerField(),
        ),
    ]
